### ISSUE TITLE
(Feature request) Automatically generate table of contents outline 

### ISSUE THREAD

**Issue by ScarletDor** [zadam/trilium#2788] opened 2022-04-15 03:18 UTC
### Describe feature

对于html和markdown等可以依据h1-h6标签自动生成目录位于侧边，以及分享页面

### Additional Information

thanks

**Comment by zadam** [comment] 2022-04-15 13:09
Closing as duplicate of https://github.com/zadam/trilium/issues/533

**Closed by zadam** 2022-04-15 13:09 UTC
Labels: Type: Enhancement

**Comment by ScarletDor** [comment] 2022-04-16 02:39
非常感谢
