### ISSUE TITLE
links not only to note but to specific line or paragraph

### ISSUE THREAD

**Issue by omega3** [zadam/trilium#1986] opened 2021-05-30 10:46 UTC
In Kate (note application from Plasma KDE) there are number lines of lines displayed
https://i.imgur.com/nrM9CKn.png
Line number / paragraph is shown at the bottom left corner of application, so that it is always visible even option to display lines is inactive.

I think it would be great if Trilium could be more precise and link note only to note but to specific line.

How about just typing this number after choosing note to link:
https://i.imgur.com/qWGt5YI.png
or separated by / for example if child note is named Highlighting and we want to point to second line:
Highlighting/2

The problem may occur when user edit note and deletes some lines but hmmm, this may be an alternative way of referring to something or users needs to pay attention how they manage their notes. Definitely for some notes that are not meant to be edited frequently it is great solution. 

Maybe line / paragraph that is being linked to could have a kind of visual indicator. 

Edit:
It appears that Obsidian has it
https://help.obsidian.md/How+to/Link+to+blocks

Very useful feature.

**Comment by kees-** [comment] 2021-05-30 16:53
Duplicate of #1948

This has been mentioned before multiple times #1948 #1704 #1021 #1233 (<- kind of) and likely others. Those are what I saw at a glance.
Clearly users find it useful but it has been stated to go against the design philosophy of the program to an extent, or at least be low priority. 

Stated definitively by @zadam [here](/zadam/trilium/issues/1948#issuecomment-841444140), very recently as well:
> Hi, linking to note sections is not supported and there isn't an immediate plan to support this. Trilium works best when used with many smaller notes instead of smaller number of longer notes.

I don't know obsidian, but it does appear to have a nice note embedding feature as well as block links. 
The ability to link to embedded notes in trilium does have a level of overlap with with header/block links already.

As far as linking to a line number, unique idea, but any possible implementation of that would be:
- precarious at best, for users who don't edit notes,
- or sloppy and broken for those who rearrange/consolidate/add to notes. I do this all the time and can't imagine a situation where that would impact my personal workflow positively.

Giving users a marginal functionality at the cost of having to think a lot more and use a tool in a certain way is questionable design practice anywhere.

**Comment by kees-** [comment] 2021-05-30 16:58
Duplicate of #1948

**Comment by omega3** [comment] 2021-06-13 16:03
> or sloppy and broken for those who rearrange/consolidate/add to notes. 
Indeed, a valid argument. But what about

**Comment by zadam** [comment] 2021-10-07 12:29
Closing in favor of ##1021

**Closed by zadam** 2021-10-07 12:29 UTC
