### ISSUE TITLE
[REGRESSION:v0.46.0-beta] Multiple bugs

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1647] opened 2021-02-16 10:02 UTC
Hi ! Still testing new beta version, i found some other bugs:

### #left-pane .tree `collapseTree` (Alt+C)
* click on **Collapse note tree** button in tree bottom works as expected
* using shortcut `Alt+C` does not work
* rewriting 'Alt+C' as shortcut value for `collapseTree` in settings changes nothing (also tried `Alt+c` & `global:Alt+C`)
* no error shown in dev tools while pressing shortcut

### #left-pane .tree `scrollToActiveNote` (Ctrl+.)
* click on **Scroll to active note** button in tree bottom works as expected
* using shortcut `Alt+C` does not work
* rewriting 'Ctrl+.' as shortcut value for `scrollToActiveNote` in settings made it work again, but partially:
  * shortcut expands tree to make active note visible, but doesn't scroll to it if tree is large
  * dev tools error appears while typing shortcut: `FancytreeNode@CyhlijNBxS2w[title='Tools'] setExpanded(true) while animating: ignored.`

### .standard-top-widget .quick-search
* `Show in full search` button does nothing if clicked
* But it works correctly if focusing with keyboard then pressed with `Enter`

### Saved searches
all existing `Saved search` notes have lost their content.
while migrating from v0.45.* to 0.46, existing saved search `search string` should be properly migrated as new saved search's `Search String` value

**Comment by nil0x42** [comment] 2021-02-16 10:29
After rewriting 'Ctrl+.' to `scrollToActiveNote` shortcut value in settings, it started working again, therefore the tree does not scroll to the location of my active note. It only expands the tree without scrolling.

For `Alt+C`, even after rewriting shortcut value, and even trying to set value `Alt+c` (with minus `c`), i could not manage to make it work.

**Comment by nil0x42** [comment] 2021-02-16 14:08
On notes from [task manager](https://github.com/zadam/trilium/wiki/Task-manager), if i show inherited attributes and click on the target note of `~runOnAttributeChange` relation to `attribute changed`, the note opens correctly.
Therefore whis weird error message appears:
```
Error when calling POST /api/search-related: 500 - notePathArray.includes is not a function
```
I tought is was worth mentioning.

**Comment by zadam** [comment] 2021-02-16 22:32
Hi, the bugs you mentioned in the original post are now fixed.

I could not reproduce "attribute changed" problem yet.

**Comment by nil0x42** [comment] 2021-02-17 05:43
Thank you ! I think the "attribute changed" issue was related to the fact that shortest path to `attribute changed` note was a path from a saved search:
`root / Github Pages / attribute changed`

As after trying v0.46.0-beta, all my `saved search` notes went empty, and started returning almost **all existing notes**, making paths a mess.

Indeed i think it would be very useful to have different behavior when a note path has a 'saved search' ancestor.
For example, the `Note paths` button should show those paths at the bottom of list (low priority), and ideally have some kind of visual marker to make more obvious that this path is "virtual".

**Closed** 2022-08-03 17:44 UTC
