### ISSUE TITLE
(Bug report) file:// and other pefixes as links not clickable

### ISSUE THREAD

**Issue by d00m514y3r** [zadam/trilium#2974] opened 2022-07-08 22:49 UTC
### Trilium Version

0.52.3

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

5.15.50-1-manjaro x64

### Description

I'm trying to create a link so that it opens a local pdf file in the browser. Creating the link makes the text blue, but it is not clickable. Also that small arrow is not present at the end of it
![image](https://user-images.githubusercontent.com/46358654/178078843-d8b10dad-fcc1-41dd-9e86-3cc756d037ba.png)
It would be great if I could go to a note and jump to it's page of reference by opening the book in the browser.

**Comment by sigaloid** [comment] 2022-07-09 00:59
This isn't a solution to your problem but it is a solution that might help you regardless - you can import the file into Trilium and just link it internally.

**Comment by zadam** [comment] 2022-07-09 11:32
Hi, this is a duplicate of https://github.com/zadam/trilium/issues/1876 caused by CKEditor issue https://github.com/ckeditor/ckeditor5/issues/8248

**Closed by zadam** 2022-07-09 11:32 UTC
Labels: Type: Bug
