### ISSUE TITLE
`New task` shortcut doesn't activate new note

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#803] opened 2020-01-02 17:02 UTC
Hello.
I use the task manager of trilium.
Since trilium 0.39.X, if i click the `New task` button, a new task is correctly created and activated.
Therefore, if i use the associated keyboard shortcut, the new task note is created, but not activated.

Here is the associated `button` note:
```js
api.addButtonToToolbar({
    title: 'New task',
    icon: 'check',
    shortcut: 'alt+n',
    action: async () => {
        // creating notes is backend (server) responsibility so we need to pass
        // the control there
        const taskNoteId = await api.runOnServer(async () => {
            const todoRootNote = await api.getNoteWithLabel('taskTodoRoot');
            const {note} = await api.createNote(todoRootNote.noteId, 'new task', '');

            return note.noteId;
        });

        // we got an ID of newly created note and we want to immediatelly display it
        await api.activateNewNote(taskNoteId);
    }
});
```

**Comment by zadam** [comment] 2020-01-02 17:51
Hello,

I suspect this is a problem where backend changes are not propagated soon enough (they are async) to the frontend which will fail the activation. I actually can't reproduce this, but that's the nature of these async problems that they happen only in some timing circumstances.

As an attempt to tackle this problem I introduced a while ago a `waitUntilSynced` API call which forces the client to synchronously sync with the backend before continuing. So I recommend changing the script in this way:

```javascript
api.addButtonToToolbar({
    title: 'New task',
    icon: 'check',
    shortcut: 'alt+n',
    action: async () => {
        // creating notes is backend (server) responsibility so we need to pass
        // the control there
        const taskNoteId = await api.runOnServer(async () => {
            const todoRootNote = await api.getNoteWithLabel('taskTodoRoot');
            const {note} = await api.createNote(todoRootNote.noteId, 'new task', '');

            return note.noteId;
        });

        // wait until the frontend is fully synced with the changes made on the backend above
        await api.waitUntilSynced();

        // we got an ID of newly created note and we want to immediatelly display it
        await api.activateNewNote(taskNoteId);
    }
});
```

Hopefully this will fix the issue.

**Comment by nil0x42** [comment] 2020-01-02 18:23
It resolved the issue, thank you !

**Comment by nil0x42** [comment] 2020-01-04 00:05
re-opening, because even with the fix, it worked the day after the fix, but now it's not working even though i added `await api.waitUntilSynced();`

**Comment by joebetsill** [comment] 2020-07-13 18:31
I have the same issue noted above. I am running Trilium using docker on my synology nas-- using the built-in docker client and the Trilium web interface. I am also using synology's reverse-proxy client. Something is introducing greater than 5000ms of latency, which according to the logs is forcing a front end refresh. 

The error occurs even when I'm not accessing the web client via the reverse proxy. (e.g., if I go to 192.168.100.77:8080) The error also occurs during a fresh install, using only the Demo notes.

The applicable part of the logs are:
```
18:00:40.952 INFO  JS Error: Encountered error Process exceeded time limit 5000: Error: Process exceeded time limit 5000
    at https://my.trilium.domain/app/services/utils.js:342:21, reloading frontend.
Stack: Error
    at logError (https://my.trilium.domain/app/services/ws.js:29:20)
    at consumeSyncData (https://my.trilium.domain/app/services/ws.js:163:13)
```
I manually edited my domain info for obvious reasons.

While I have no idea what's causing this latency, a short term fix might be to give the option to extend the time before the refresh, similar to the options when setting up a non-local server.

**Comment by zadam** [comment] 2020-07-14 19:55
Hi @joebetsill , thanks for reporting this issue. Could you specify more closer which operation (like editing the title, moving the note etc.) for example triggers this error (and reload) on the demo document?

**Comment by joebetsill** [comment] 2020-07-15 00:44
When I press the "New Task" button. Most times I can see the GUI switch to the newly created note, but less than a second later the whole front end refreshes and I'm back at whatever I was looking at before I pressed the "New Task" button.

I was tinkering with the button itself and the command that creates the new task is what is taking so long; I commented out the code to wait for the sync and the code to switch to the newly created task.

For reference, this code here is what is causing the refresh:
```
async () => {
        // creating notes is backend (server) responsibility so we need to pass
        // the control there
        const taskNoteId = await api.runOnServer(async () => {
            const todoRootNote = await api.getNoteWithLabel('taskTodoRoot');
            const {note} = await api.createNote(todoRootNote.noteId, 'new task', '');

            return note.noteId;
        });
```

It happens 100% of the time for me, across multiple platforms (on my windows machine and my chromebook) so if there's any other tests you'd like me to run let me know. I understand how difficult it is to run down an issue that you can't re-create.

**Comment by zadam** [comment] 2020-07-15 20:38
@joebetsill I managed to reproduce this on the "New task" button and this bug is now fixed, so I'm going to close this issue.

Thanks for help!

**Closed by zadam** 2020-07-15 20:38 UTC
Labels: Type: Bug
