### ISSUE TITLE
ghost triangles populate print note to PDF

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#1129] opened 2020-06-24 12:36 UTC
hello,

no idea where in the pipeline this could be caused; but in result I have black triangles in any printed PDF (also in postscript file). 
– it seems this is unrelated to images being formatted as columns / non-fullwidth images (which was my first suspicion; some kind of spatial placeholders causing this).

would of course be nice if these could be made to disappear as I currently use PDF as favorite exporting format  :-)

thx for any hint / lead on this!
oliver
[Trilium Notes - Aby Warburg - Mnemosyne - Das Original (HKW 2020).pdf](https://github.com/zadam/trilium/files/4825328/Trilium.Notes.-.Aby.Warburg.-.Mnemosyne.-.Das.Original.HKW.2020.pdf)
<img width="709" alt="Trilium Notes - Aby Warburg - Screenshot - 2020-06-24 14 12 32" src="https://user-images.githubusercontent.com/11589804/85555811-900cec80-b626-11ea-9dd9-f98621f803d9.png">

**Comment by zadam** [comment] 2020-06-24 18:44
Hi, thanks for reporting this issue, it's now fixed.

This was caused by recent CKEditor upgrade which added "type around" controls for images but caused these weird triangles in PDF.

**Closed** 2020-06-24 18:44 UTC

**Comment by D-Walter** [comment] 2023-11-26 13:17
> Hi, thanks for reporting this issue, it's now fixed.
> 
> This was caused by recent CKEditor upgrade which added "type around" controls for images but caused these weird triangles in PDF.

Hi, thanks for your work. I noticed that the ghost triangle reappeared in version 0.62.2. Any suggestions on how to deal with this?

**Comment by zadam** [comment] 2023-11-27 08:33
@D-Walter could you post a screenshot with the triangles? Does the note have math formulas? 0.62.2 has a printing regression, but it's specific to math: #4470
