### ISSUE TITLE
(Bug report) Error pasting part of the text from input boxes into Trilium.

### ISSUE THREAD

**Issue by easydigi** [zadam/trilium#4159] opened 2023-08-11 06:06 UTC
### Trilium Version

0.61.4-beta

### What operating system are you using?

macOS

### What is your setup?

Local (no sync)

### Operating System Version

13.4.1 (22F82)

### Description

This version does not seem to have resolved this issue yet. An error still occurs when pasting text copied from input and textarea elements in the browser.

### Error logs

ws.js:18 14:06:01 Uncaught error: Message: Uncaught CKEditorError: Cannot read properties of null (reading 'map')
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-Cannot read properties of null (reading 'map'), URL: , Line: 6, Column: 382018, Error object: {"name":"CKEditorError","context":{}}, Stack: TypeError: Cannot read properties of null (reading 'map')
    at Object.<anonymous> (<anonymous>:6:1261272)
    at Object.fire (<anonymous>:6:383577)
    at Cs (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Object.<anonymous> (<anonymous>:6:922689)
    at Object.fire (<anonymous>:6:383577)
    at Cs (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Rw.fire (<anonymous>:6:511653)
    at Rw.onDomEvent (<anonymous>:6:923529)

VM366:6 Uncaught TypeError: Cannot read properties of null (reading 'map')
    at Object.<anonymous> (<anonymous>:6:1261272)
    at Object.fire (<anonymous>:6:383577)
    at Cs (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Object.<anonymous> (<anonymous>:6:922689)
    at Object.fire (<anonymous>:6:383577)
    at Cs (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Rw.fire (<anonymous>:6:511653)
    at Rw.onDomEvent (<anonymous>:6:923529)

**Comment by TheBenMeadows** [comment] 2023-08-13 19:33
Same. Having this issue still.

**Comment by easydigi** [comment] 2023-08-14 02:52
> Same. Having this issue still.

Yes, but 61.4 seems to have improved compared to previous versions.

**Comment by zadam** [comment] 2023-08-15 08:38
It seems there were two independent copy-paste bugs with different root causes - one was fixed in 0.61.4-beta, the other was fixed yesterday.

**Closed by zadam** 2023-08-15 08:38 UTC
Labels: Type: Bug
