### ISSUE TITLE
Ctrl-Z copied note contents into another note

### ISSUE THREAD

**Issue by jbhanks** [zadam/trilium#766] opened 2019-12-12 21:22 UTC
I thought ctrl-Z was supposed to undo actions. However I was just undoing by pressing ctrl-Z a few times, and the contents of a different note suddenly replaced the contents of the note I was undoing on. This means the "undo" took the note to a state it had never been in. 
I was able to recover my note by going into history and copying the contents of a previous version, but I'd like to understand how this happened. Is this a bug or an error/misunderstanding on my part.

**Comment by zadam** [comment] 2019-12-13 09:09
Hello, what you are observing is not an intended behavior and is probably an editor bug.

It happens probably because we're reusing ckeditor instances instead of creating new one everytime, but then again this should be fine and the undo history should not be leaking between these usages.

I cannot reproduce this though ...

**Comment by jbhanks** [comment] 2019-12-13 19:27
I'm not going to try too hard to reproduce it, but I will try and pay closer attention to the circumstances if it happens again.

**Comment by jbhanks** [comment] 2020-03-10 21:23
This just happened again.
I cut the contents of a note called "quick access" and pasted it into another note called "dummy data". I then changed the note type of "dummy data" from text to markdown and started editing the auto-generated markdown. When I realized that it was going to be awkward, I decided to backtrack and hit ctrl-Z a couple times. This resulted in the appearance to text from another note called "Shell" in "dummy data".  I'm fairly sure that this data had never been in "dummy data" although I was editing "Shell" recently (last night, on another machine).

**Comment by zadam** [comment] 2020-03-10 21:50
Hello, the critical piece of information I was missing was that this was happening the code note. I was unsuccessfully trying to reproduce this in the default text note ...

But from your last comment (mentioning markdown...) this became clear and reproducing and fixing this bug was now easy. Thanks for reporting, this will be fixed in next bugfix release.

**Closed by zadam** 2020-03-10 21:50 UTC
