### ISSUE TITLE
[0.39.3] Note is not saved when inserting another note in an empty note

### ISSUE THREAD

**Issue by louwers** [zadam/trilium#807] opened 2020-01-03 22:57 UTC
1. Open empty note (optionally with a title)
2. Insert a note
3. Go to other note
4. Go back, the inserted note will be gone

If you type something else in the note before you leave the note is saved properly.

**Comment by zadam** [comment] 2020-01-04 07:44
Hello, I cannot reproduce this but maybe I don't fully understand it. What does "inserted note will be gone" mean exactly? The note is missing from the left note tree or you can click on it but it does not display anything or something else?

**Comment by louwers** [comment] 2020-01-04 11:03
I mean to insert a note inline. Here's a screencast:

![bug](https://user-images.githubusercontent.com/649392/71764609-2408c180-2eea-11ea-9a53-27a93e25d443.gif)

**Comment by zadam** [comment] 2020-01-04 12:23
Thank you for the recording, this made it clear to me. Trilium detected incorrectly the note as empty when it contained only "include note" widget and did not save it. This is now fixed and will be released in patch version soon ...

**Closed by zadam** 2020-01-04 12:23 UTC
