### ISSUE TITLE
(Bug report) Evernote import damages inline files

### ISSUE THREAD

**Issue by avidrissman** [zadam/trilium#3497] opened 2023-01-08 03:39 UTC
### Trilium Version

0.57.5

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

macOS Ventura 13.1 (22C65)

### Description

This enex was written by v7.14.1 of the Mac version of Evernote Legacy:
[image.enex.zip](https://github.com/zadam/trilium/files/10367642/image.enex.zip)

Repro:
- Do an “Import into note” of that file

Expected:
- A note with a 851,834 byte JPEG file

Actual:
- A note with a 778,432 byte JPEG file

I can repro this locally with PDF files, mp4 files, etc. Most of the notes that I tested for import encountered this corruption. This .enex file is one of the few that isn’t personal, and is suitable for bug reporting purposes.

Note that if I strip the raw b64 bytes out of the enex file and manually decode them with the commandline `base64`, it decodes correctly, so I know that the importing process is doing the damage.

What was the source of the enex files that you built the Evernote import on? Given #3496, you might have a more general problem with enex files created by the Mac version of Evernote Legacy; I would be happy to provide you with more sample files if needed.

**Comment by zadam** [comment] 2023-01-08 12:00
Hi, looks like the same issue as in https://github.com/zadam/trilium/issues/3424 which was fixed in 0.58.X.

Interestingly for me the import works also in 0.57.5, I think it might be partially platform-specific:

![image](https://user-images.githubusercontent.com/617641/211194927-e3716fc6-419b-471d-a64d-ab8a09c25dc5.png)

**Comment by avidrissman** [comment] 2023-01-08 16:54
Already fixed is good to hear. I spun up 0.57.5 because that’s what Docker gave me for

```
services:
  trilium:
    image: zadam/trilium
```

Hmmm.

Will wait for #3496 to roll into a Docker and then will update. Can confirm this then.

**Comment by avidrissman** [comment] 2023-01-12 04:47
I can confirm this works with 0.58.4.

How OK are you with me filing issues with the Mac legacy version’s import? Apparently the new versions of Evernote export slightly different .enex files than the legacy version. The problem is that the new versions will only export 50 notes at a time as .enex, which is a bottleneck for people migrating away, but the legacy version will export as many notes in an .enex as you want.

**Comment by Nriver** [comment] 2023-01-12 05:06
You can try export with this https://github.com/vzhd1701/evernote-backup

**Comment by zadam** [comment] 2023-01-12 06:11
> How OK are you with me filing issues with the Mac legacy version’s import?

I'm fine with that, especially if you provide ENEX to reproduce the issue. The difference so far have been quite minor and easy to fix.

**Comment by avidrissman** [comment] 2023-01-12 12:34
Thanks! This is confirmed so closing.

**Closed** 2023-01-12 12:34 UTC
Labels: Type: Bug
