### ISSUE TITLE
(Bug report)  Maybe? Day note opens with Edited Notes expanded

### ISSUE THREAD

**Issue by mattcartycodes** [zadam/trilium#4151] opened 2023-08-08 07:49 UTC
### Trilium Version

0.60.4

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Pop_OS 22.04

### Description

Since perhaps yesterday, when I open and day note, the edited notes list opens expanded. If I collapse it, close the note, and re-open it, it opens expanded again. 

Non day-notes open with all attributes collapsed, it's only an issue for the day notes. I did recently get rid of the weight tracker, I'm not sure if this is related. Not totally sure it is a bug.

**Comment by zadam** [comment] 2023-08-09 20:51
It is connected to the weight tracker removal - that one had a "promoted label" which had a priority. Now that it's gone, the edited notes are getting displayed on day notes.

This is not a bug, but given that this is not the first time somebody asked about it, I've added an option to disable the auto-opening:  
 

![](https://github.com/zadam/trilium/assets/617641/22507d6d-ea73-48a0-987b-bf0d7c86800c)

will be in the next 0.61 release.

**Closed** 2023-08-09 20:50 UTC
Labels: Type: Bug

**Comment by mattcartycodes** [comment] 2023-08-12 07:46
Thank you! Apologies for labelling it a bug
