### ISSUE TITLE
请问如何随意打开编辑模式，可以设置这个的快捷键吗？

### ISSUE THREAD

**Issue by MCX-gtf** [zadam/trilium#1857] opened 2021-04-16 19:30 UTC
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by zadam** [comment] 2021-04-16 20:27
duplicate of #1858

**Closed by zadam** 2021-04-16 20:27 UTC
