### ISSUE TITLE
[Feature Request] CKEditor Horizontal Line

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1164] opened 2020-07-30 05:42 UTC
Hi, I would love to have a horizontal line option. Looks like there is a [CKEditor plugin](https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html) for this

**Comment by estasney** [comment] 2020-08-01 20:18
I was able to add this to CKEditor in Trilium. It wasn't as straightforward as I initially thought. Here's what I did if you want to replicate:

### Rebuild [ckeditor.js](https://github.com/zadam/trilium/blob/master/libraries/ckeditor/ckeditor.js)
This part was a bit confusing. Since Trilium contains custom plugins it needs to be built with those included. Those aren't included in this repo.

Those seem to be located here [trilium-ckeditor-build](https://github.com/zadam/trilium-ckeditor-build). 

1. Modify ckeditor.js (*trilium-ckeditor-build repo*)
  i. [Import HorizontalLine](https://github.com/estasney/trilium-ckeditor-build/blob/1ba073dfca8ea379d7c881b347fb5a157ab8d675/src/ckeditor.js#L48)
  ii. [Add to defaultPlugins](https://github.com/estasney/trilium-ckeditor-build/blob/1ba073dfca8ea379d7c881b347fb5a157ab8d675/src/ckeditor.js#L103)
  iii. [Configure blockToolbar](https://github.com/estasney/trilium-ckeditor-build/blob/1ba073dfca8ea379d7c881b347fb5a157ab8d675/src/ckeditor.js#L148-L159)
 
2. Build ckeditor.js
  i. I had an issue where `npm run build` would succeed, but CKEditor would throw `ckeditor-duplicated-modules` when loaded in a browser.
ii. I was finally able to get this to work after using [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) and using [these versions](https://github.com/estasney/trilium-ckeditor-build/blob/1ba073dfca8ea379d7c881b347fb5a157ab8d675/package.json#L27-L66)

3. Replace the ckeditor.js in trilium with the newly built ckeditor.js from trilium-ckeditor-build
  i. [My Fork](https://github.com/estasney/trilium-ckeditor-build/tree/master/build)

![image](https://user-images.githubusercontent.com/16440579/89109813-96a33680-d412-11ea-8129-02936508ab26.png)

**Comment by zadam** [comment] 2020-08-01 21:33
@estasney, hi, your problems were (at least partially) caused by the usage of old repo for ckeditor. Trilium now uses https://github.com/zadam/trilium-ckeditor5 to build CKEditor. Reason for the switch was migration of the CKEditor 5 from repo-per-package to monorepo. I archived the old repo to make this clear.

**Comment by zadam** [comment] 2020-08-01 21:42
I ported your changes to the correct repository and made the build, HR is now available in stable branch and will be in the next release. Thanks!

**Closed by zadam** 2020-08-01 21:42 UTC

**Comment by estasney** [comment] 2020-08-01 22:01
> @estasney, hi, your problems were (at least partially) caused by the usage of old repo for ckeditor. Trilium now uses https://github.com/zadam/trilium-ckeditor5 to build CKEditor. Reason for the switch was migration of the CKEditor 5 from repo-per-package to monorepo. I archived the old repo to make this clear.

Thanks for pointing this out @zadam I saw the archived repo under your Popular Repositories - didn't think to look further. Glad I could contribute, I'm a big fan!

**Comment by Engr-AllanG** [comment] 2020-08-02 02:36
@estasney , @zadam - Much thanks!

**Comment by nil0x42** [comment] 2020-08-28 15:56
Thank you guys !

**Comment by Engr-AllanG** [comment] 2020-08-28 17:43
Yes, this is great! Thanks for adding 
⁣-Allan
