### ISSUE TITLE
[BUG] Same label (from same parent) inherited multiple times

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#735] opened 2019-12-01 14:04 UTC
Hi ! I was testing the now version of alwaysVisible widget @jhc86 wrote [here](https://github.com/zadam/trilium/issues/715), and i found this issue:

On some notes, the widget appears 2, 3, or even 4 times (depending on the note).
After checking the labels with `Alt+A`, i discovered that the `alwaysVisible` label, that i've put in root and made inheritable, in some cases is inherited multiple times, probably because a lot of my notes are cloned, and then have multiple paths leading to root.

Here is a screenshot of the inherited attributes of one of my notes:
![Screenshot_2019-12-01_13-58-38](https://user-images.githubusercontent.com/3504393/69915118-5df62c00-1443-11ea-9ae9-03963bc0bc77.png)

As you can see, the same label, from the same note, ends up being inherited 4 times here (and the widget appears then 4 times)

**Comment by zadam** [comment] 2019-12-02 19:10
Hello, thanks for report. You're right this was caused by cloning - there was multiple paths leading to the same attribute. This has been fixed in master but I will also port it to stable branch.

**Closed** 2019-12-02 19:10 UTC
