### ISSUE TITLE
(Bug report) Issue with overwriting tags/relationships while using specific shortcuts

### ISSUE THREAD

**Issue by YestermorrowONill** [zadam/trilium#4077] opened 2023-07-03 07:07 UTC
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11

### Description

When using the shortcuts Alt+L or Alt+R consecutively to create tags or relationships, the previously edited tags or relationships are automatically carried over to the current note. This issue does not occur when the shortcuts are not used. Additionally, it even results in the current note’s edited tags being overwritten by the previously edited ones. This issue has been present since very early versions.

Could you please assist in resolving this issue? Thank you!

**Comment by zadam** [comment] 2023-07-09 21:06
Hello, would it be possible to record a screencast? I'm not able to reproduce this ...

**Comment by YestermorrowONill** [comment] 2023-07-10 02:34
Sorry, I’m not able to upload videos at the moment. However, it is easy to reproduce this issue. My previous description may not have been accurate, which led to your inability to reproduce the problem. Here are the steps to reproduce the issue:

1. Create a note A and use Alt + L to create a tag, for example, alias = test.
2. Create a second note B and use Alt + L to try to create a tag, and you will notice that the tag from step 1 appears in the second note.

**Comment by zadam** [comment] 2023-07-15 07:19
Unfortunately still no success. If you press Alt+L, it will create a label with the default name "myLabel". But other than that I don't see how the label is being copied from the note A to note B :-(

**Comment by YestermorrowONill** [comment] 2023-07-17 02:27
![issue](https://github.com/zadam/trilium/assets/41185496/f71b8525-ecb9-43fd-856e-d22c930fc29a)
@zadam

**Comment by zadam** [comment] 2023-07-17 20:37
Thanks. The part I was missing is that you press ALT+L without first activating the "Owned attributes" ribbon tab. Now I can reproduce the issue.

**Comment by zadam** [comment] 2023-07-17 20:41
Fixed, will be in 0.61.

**Closed by zadam** 2023-07-17 20:41 UTC
Labels: Type: Bug
