### ISSUE TITLE
close last tab page

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#2298] opened 2021-11-01 03:00 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

I noticed in the latest 0.48.4 that the last tab page can not be closed. In previous versions, last page was closable. Would you add an option for this config?

**Comment by agentydragon** [comment] 2021-11-01 07:03
I think this is duplicate of https://github.com/zadam/trilium/issues/2212.

**Comment by Nriver** [comment] 2021-11-01 07:29
> I think this is duplicate of #2212.

No, not the same actually. I want to keep Trilium running even if the last tab is closed, just like the how 0.47 works.

I think ctrl+w should handle only tabs, not close the application. ctrl+q is the one to close the whole application.

**Closed** 2021-11-01 07:38 UTC
Labels: Type: Enhancement

**Comment by zadam** [comment] 2021-11-01 07:39
Hi, the way it was done before (closing and opening new empty tab) was prone to race conditions when closing the tabs quickly, that's why I changed the behavior.

I've now made a change which simulates the old behavior - it doesn't close the last tab, just opens the empty screen which is functionally (almost) the same thing.
