### ISSUE TITLE
Question about search results

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1301] opened 2020-10-11 13:50 UTC
Hi Zadam
I found it's no more possible to watch notes on Saved Search (Test on 0.44.6)
For example, the results I found is A B C D. However, I just wanna see A in the Saved Search instead of jumping to the A branch alone.When I click on A result the program that redirects me to A note branch(It expandes all subtrees to find A note. In order to see all the search results, I need to jump around a lot to each result.).
I think the older version even I click It wont jump to the A note branch.(Them are just shown in the Save Search)
I don't know if it can be set manually
Waiting for a reply
Thanks

**Comment by zadam** [comment] 2020-10-20 20:35
Hi, this "jumping" is actually not intended behavior and is a bug instead. However, the fix is not easy and because of potential for regressions it will be in 0.45.

**Closed by zadam** 2020-10-20 20:35 UTC
