### ISSUE TITLE
Sharing is Awesome.......But missing search .....

### ISSUE THREAD

**Issue by passionate2023** [zadam/trilium#3602] opened 2023-02-11 04:18 UTC
### Describe feature

Sharing is Awesome.......But missing search .....

It would be very great to include search for the shared notes

**Comment by sigaloid** [comment] 2023-02-11 06:35
Duplicate of #3346 #3405 #3430 #3570

**Comment by zadam** [comment] 2023-02-11 20:27
Tracked in https://github.com/zadam/trilium/issues/3430

**Closed by zadam** 2023-02-11 20:27 UTC
Labels: Type: Enhancement
