### ISSUE TITLE
[Bug?] Test sync with server returns TypeError

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1742] opened 2021-03-13 14:17 UTC
I've been running the  0.46.4-beta desktop version, and am now trying to set up a server instance to sync with.

I have a Traefik reverse proxy setup and run a container based on the 0.46.4-beta Docker image. Accessing the server in a browser is no problem, but when testing the synchronisation from the desktop app, I get a TypeError back:

![image](https://user-images.githubusercontent.com/39531/111032968-2e3c1f00-840f-11eb-8c0e-02f2e986da19.png)

Am I missing something, or is this a bug?

**Comment by zadam** [comment] 2021-03-13 21:55
Hi, thanks for reporting this issue!

Looks like a regression in 0.46 affecting setting up the sync from client to server. It has been fixed and will be in the next release.

**Closed** 2021-03-14 18:53 UTC
