### ISSUE TITLE
(Bug report) Canvas note `save as image` got error

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#2883] opened 2022-05-30 06:38 UTC
### Trilium Version

0.52.0-beta

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Manjaro

### Description

I just tried to play with canvas note in a brand new standalone client without server.

Create a new canvas note. Draw something in it. Click `save as image` on upleft, then click on png or svg. An error message will popup.
```
The request is not allowed by the user agent or the platform in the current context. 
```

I've tried Excalidraw oneline demo https://excalidraw.com/ in my browser without problem.

**Comment by zadam** [comment] 2022-05-30 11:46
Hi, I can't reproduce this on Ubuntu. Does this happen on the desktop build or local web server (which browser)? It seems to be a permission problem, do you perhaps have flatpack/appimage browser or some special security setup?

**Comment by Nriver** [comment] 2022-05-30 11:56
I use linux desktop build. Haven't check out the server or browser yet.

**Comment by zadam** [comment] 2022-05-30 14:54
Ok, weird. For me it works in both desktop build and local web server.

**Comment by thfrei** [comment] 2022-06-01 06:17
I can reproduce it with the windows Desktop Build. From the browser it works. Strange:

![grafik](https://user-images.githubusercontent.com/7283497/171339934-68f8b21b-ca66-4030-b3d4-9b58ecdbc8d1.png)

I'll investigate it.

**Comment by thfrei** [comment] 2022-06-01 06:31
Ok, it seems to be something with Chrome in Electron I think.
See here: https://github.com/excalidraw/excalidraw/issues/5100#issuecomment-1113995395

Maybe we need to enable file editing in Electron? Something like?
- https://stackoverflow.com/questions/32780726/how-to-access-dom-elements-in-electron
- https://stackoverflow.com/questions/66661551/writing-to-files-using-file-system-access-api-fails-in-electron-create-react-a

I think, Electron might use some kind of os-specific file picker, and then this process tries to access DOM Elements, which is not allowed from the outside.

As a side note, you can somehow get the image, when you share the note, and then click on `Get image link at the bottom`. It is not super user friendly yet ;-)

**Comment by capi** [comment] 2022-06-10 20:02
As a workaround: what works fine is "Export to clipboard". What also works fine: Select everything, copy to clipboard, past directly in https://excalidraw.com and save from there. But yes, it would be great to be able to export the images directly from Trilium.

**Comment by thfrei** [comment] 2022-07-08 22:29
Excalidraw just released a new version 0.12.0 yesterday. I think they fixed something that might be related to it, too. I'll update excalidraw asap and then we'll see if the issue persists. (a lot of new features like eraser, pinch zoom in view, etc.)

**Comment by Lewiscowles1986** [comment] 2022-08-07 14:31
Just a note on this. I Can export a `.excalidraw` file just fine. I Cannot save png or svg. I concur with @thfrei that this may well be an excalidraw issue. One thing I've used before to overcome these limitations is to simply create a link with a download attribute, and allow the user to click on that with a data-uri.

Really cool project though!

**Comment by thfrei** [comment] 2022-08-15 19:30
Update: Issue persists on trilium: 0.54.2 with excalidraw 0.12.0 :-(

```
The request is not allowed by the user agent or the platform in the current context.
```

**Comment by deskl0** [comment] 2023-10-13 02:53
FYI: same issue on windows 11 pro 22H2 with desktop build(0.60.4), so, it presists so far

**Comment by rauenzi** [comment] 2023-10-13 05:16
See #4271 for more info

**Comment by zadam** [comment] 2023-10-18 21:36
Closing in favor of [#4271](https://github.com/zadam/trilium/issues/4271)

**Closed by zadam** 2023-10-18 21:36 UTC
Labels: Type: Bug
