### ISSUE TITLE
A backlink to a parent directory cause a rendering error 

### ISSUE THREAD

**Issue by nerton1** [zadam/trilium#4457] opened 2023-11-20 06:42 UTC
### Trilium Version

0.61.14

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

6.6.1-arch1-1

### Description

A backlink to a parent directory now cause a rendering error 

![Screenshot_20231120_032935](https://github.com/zadam/trilium/assets/121178081/138b39fb-205d-43b7-9813-aff0af7a4cd7) 

![Screenshot_20231120_032905](https://github.com/zadam/trilium/assets/121178081/97bac10a-a93b-4f2f-84da-4987cf4eeda9)
last version: release 0.61.12

![Screenshot_20231120_033144](https://github.com/zadam/trilium/assets/121178081/e20cb662-197d-4cf3-babe-1b5a6ea0bbaf)

**Comment by Nriver** [comment] 2023-11-20 06:55
Duplicate of https://github.com/zadam/trilium/issues/4443

This is already fixed but not released yet. We can wait for the next release.

**Comment by zadam** [comment] 2023-11-20 22:18
Release incoming ...

**Closed by zadam** 2023-11-20 22:18 UTC
Labels: Type: Bug
