### ISSUE TITLE
Add mobile app (Feature request) 

### ISSUE THREAD

**Issue by patchint** [zadam/trilium#3047] opened 2022-08-08 11:20 UTC
### Describe feature

Create Android and iOS app using WebKit or directly by using Testflight

**Comment by zadam** [comment] 2022-08-08 11:48
Contributions are welcome 🙂

**Comment by meichthys** [comment] 2022-08-16 19:52
See here for some discussion: https://github.com/zadam/trilium/discussions/2990

**Comment by meichthys** [comment] 2022-09-15 01:28
Duplicate of #2953

**Closed** 2022-11-06 12:58 UTC
Labels: Type: Enhancement
