### ISSUE TITLE
Code Preview No so well in imported markdown file

### ISSUE THREAD

**Issue by xuhuanfeng** [zadam/trilium#418] opened 2019-02-22 01:46 UTC
Hi, guys

I love this awesome tools, but it seem not work so  well in uploaded markdown file for the source code. 
![](http://ww1.sinaimg.cn/large/b162e9f4gy1g0eyhyw2akj215s03ht8x.jpg)

I think it would be better to format the code into several line instead of just one line :)

**Comment by zadam** [comment] 2019-02-22 08:40
Hello, yes, this is a current limitation of the text editor component (CKEditor) that it doesn't process inline code well. I hope this is going to be fixed soon-ish ...

**Comment by pboos** [comment] 2019-05-17 11:38
possible duplicate of #379

**Closed** 2019-08-01 03:57 UTC
