### ISSUE TITLE
[BUG] Trilium freezes when opening a PDF file attached to a note on i3wm

### ISSUE THREAD

**Issue by Geosearchef** [zadam/trilium#1833] opened 2021-04-07 11:06 UTC
I have a PDF file attached to a note, which is displayed in the electron app just fine. As soon as I click open, my PDF viewer (evince) starts and shows the file just fine. Till I close it, Trilium remains unresponsive (it seems to be running normally, e.g. smooth auto hide of the pdf viewers controls works, but my cursor stays in the click on link mode and the app doesn't respond to any clicks or keyboard input).

https://gist.github.com/Geosearchef/bb5499e434b8fbcce1f151c01fd5fdc7

**Comment by zadam** [comment] 2021-04-07 20:47
Hello, so do I understand it correctly that after closing Evince, Trilium gets unfrozen and works fine?

That sounds strange. Unfortunately I can't reproduce it on my PC (Ubuntu 20.10, opening also with Evince).

**Comment by Geosearchef** [comment] 2021-04-07 21:19
Yes, as soon as evince terminates, it's working correctly again. Seems like some thread is getting blocked, although the (chromium) PDF viewer UI keeps updating.

I'm running Fedora with i3 as desktop manager, actually didn't test a different one yet, will try on Gnome later and report back.

**Comment by Geosearchef** [comment] 2021-04-07 22:48
I can confirm this only happens using i3, I cannot reproduce it using gnome. I'll continue investigating why this happens. (not sure yet if it's due to i3 or the trilium app / electron, haven't observed that issue yet with any other application or electron app)

**Comment by gerroon** [comment] 2021-04-24 17:14
Was not there an inline pdf viewer before? It seems like the pdfs are "downloaded" when clicked on open? Another issue that might be related is, Trilium tries to open alll pdfs files under a note a when clicked on the note.

**Comment by zadam** [comment] 2021-04-24 18:28
@gerroon that's an unrelated bug present only in 0.47.1 beta, I assume that's where you see it.

**Closed** 2022-08-03 17:53 UTC
