### ISSUE TITLE
(Bug report) The files create separate notes !

### ISSUE THREAD

**Issue by Mike6547** [zadam/trilium#4095] opened 2023-07-14 20:14 UTC
### Trilium Version

0.60.4

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Manjaro

### Description

Hi, I'm new to trilium and I'm having a problem that I can't seem to solve...

When I try to add a video or a file to a note, they create their own notes when I just want to integrate them into the current note!

I'm sorry to bother you, but I've been trying to fix this problem for over an hour, but I just can't seem to get it right.

Is it my version of Trilium that has a bug?

**Comment by XXXJetfireXXX** [comment] 2023-07-14 23:16
> Trilium has had a design philosophy “everything is a note” where “note” should be understood as an object placed into the note hierarchy. As a result, image is a note of type “image”, is placed into a tree, can be moved around, cloned etc.

Since this paradigm tends to confuse users, especially the new ones, the problem is already being adressed. See: #3682

**Comment by zadam** [comment] 2023-07-15 09:33
As mentioned by @XXXJetfireXXX, this is already worked on / implemented in branch and will be released soon in 0.61.

**Closed by zadam** 2023-07-15 09:33 UTC
Labels: Type: Bug

**Comment by Mike6547** [comment] 2023-07-15 19:38
Thank you very much for your work, because I really thought it was a bug. I'd really like to use the version that fixes this problem, as I think Trilium has a lot of potential!
