### ISSUE TITLE
Javascript error on import of large 1gb ENEX file.

### ISSUE THREAD

**Issue by andymend** [zadam/trilium#659] opened 2019-10-12 21:37 UTC
Attempting to import a large Evernote file in ENEX format, Trilium 0.35.2 on Ubuntu 18.04 throws an error: A Javascript error occurred in the main process. Uncaught exception. TypeError: Cannot read property 'toString' of undefined at SAXStream write (/user/lib/trilium/resources/app.asar/node_modules/sax/lib/sax.js:239:29).... 
I'm attaching a screenshot with the complete error message and the log as requested.

![trilium-error-Screenshot_20191012_142739](https://user-images.githubusercontent.com/33438768/66707947-bccddd80-ecfd-11e9-92e1-b3a662231d1a.png)

[trilium-2019-10-12.log](https://github.com/zadam/trilium/files/3721179/trilium-2019-10-12.log)

**Comment by zadam** [comment] 2019-10-13 18:22
Hello, thanks for the bug report.

Unfortunately this is quite deep in the 3rd party library code and it's not clear what the root cause might be. Chances are low but worth asking - would it be possible to share the enex file which causes this issue? You could send me link privately to zadam.apps@gmail.com.

**Comment by zadam** [comment] 2019-12-21 13:28
Closing because of no feedback.

**Closed by zadam** 2019-12-21 13:28 UTC
