### ISSUE TITLE
[Desktops] Menus are unresponsive 

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#1018] opened 2020-05-14 00:34 UTC
Hi

I am using this on Linux and Windows. The new versions (0.42.2) seems to be crippled after couple minutes of opening with the message below, the developer console is filled with the log below, pretty much every second.

Trilium works only within the first couple minutes of opening or trying to do manual sync. This was not the case with the prev versions.

The menus do not respond, clicking on notes do not open any notes as if the whole ui is some kind of ghost ui. The solution is to restart.

```
19:32:10 Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.
```

**Comment by gerroon** [comment] 2020-05-14 00:45
Ok

The server appearantly dies and was not starting properly due to the server port's was being in use by some zombie process. Killing it prtoperly and starting it back resolevs this issue.

However it would be nice if the clients do not die because of a malfunctioning server back backend.

**Comment by zadam** [comment] 2020-05-14 11:11
Hmm, as I understand this happened with the desktop builds while they were unsuccessfully trying to connect to the server instance?

It kind of looks like the backend process was hanged because of the sync process. Could you perhaps post backend logs from the desktop instance where this was happening? Either here or at zadam.apps@gmail.com

Thanks!

**Comment by gerroon** [comment] 2020-05-14 15:41
I am pretty sure that the dead server  was causing the issue becasue both the Windows and the Linux apps had the same issue at the same time and I was able to repeat the issue when I pressed sync on both apps.

My guess is that the server port 4090 was still open or part of the process that was responsing over 4090 was still open so the clients thought that they were talking to the server as usual, however the server app was on life support it seemed, and everything got back to normal once I killed all the remaining server processes and restarted it.  I was not able to restart the server initially because the port :4090 was in use by "3252270/./node/bin/" which I had to kill to restart.

**Comment by gerroon** [comment] 2020-06-01 21:51
Hitting this again. 

The server crashes hiddenly and when that happens all the clients become unresponsive. This can be only resolved if I am able to login and restart the server.

It would be very very nnice if the clients are less dependant on the server or somehow failed syncs do not make the clients useless.

The server crashes somehow and somehow it still occupies , therefor trying to restart it using the "supervisor" which is what I use to control the processes here does not work, the process has to be killed first.

`:4090          10.2.0.11:43126         ESTABLISHED 882733/./node/bin/n`


In any case I do not understand why failed server backend renders the all clients useless. Cant they just fail the sync only instead of being a zombie ui shell?

**Comment by zadam** [comment] 2020-06-13 10:57
Hello, I managed to reproduce this issue in context from #1093 and now this has been fixed and will be released soon. Thanks for reporting!

**Closed by zadam** 2020-06-13 10:57 UTC
