### ISSUE TITLE
Menu tree behaviour

### ISSUE THREAD

**Issue by jaroet** [zadam/trilium#810] opened 2020-01-06 07:34 UTC
I run 0.39.4 release on a Mac and the menu tree is behaving strangely. 
When wanting to sort a tree-branch I tried it first with the right-click menu. But I was unable to choose the sort option. 
Only later I saw that I need to scroll to the right (vague scroll-bar at the bottom). This is very unlogical in my opinion. Is it suppose to work like that?

**Comment by zadam** [comment] 2020-01-06 16:10
Hello, could you please post a screenshot of how you can't choose the sort option?

**Comment by jaroet** [comment] 2020-01-06 17:38
Hello, I have uploaded a small (3Mb) movie of the issue on my google Drive. You can download if from [here](https://drive.google.com/file/d/10IXkyGT2ZCZJnOwo-g1AO09j9n2NO7f8/view?usp=sharing).  I was not able to play it from the drive directly. 

I have never seen such a scroll action needed in any application.  I saw another issue about the right click menu falling of the screen so I do understand why it is done like this but I would expact all menu commands to be in one list within a scrollable windows/popup.

Regard,
JeRoen

**Comment by bwat47** [comment] 2020-01-07 17:46
This seems to happen with anything that has a 'sub' menu in the right click menu (e.g. it also happens with the 'insert note after' submenus).

In my case, I can't even access the submenu at all. If I move my mouse down to the scrollbar that appears at the bottom, it disappears before I can grab it. If I try to use the mouswheel scroll, it only scrolls up/down not right/left

**Comment by jaroet** [comment] 2020-01-07 19:46
> This seems to happen with anything that has a 'sub' menu in the right click menu (e.g. it also happens with the 'insert note after' submenus).

Indeed ... like I show in the movie. A mac mouse has very easy horizontal scrolling. Your mouse has not I guess.

**Comment by zadam** [comment] 2020-01-07 19:56
Hello, thank you for reporting this bug - this was not intended behavior and is now fixed. This is how it should look like:

![image](https://user-images.githubusercontent.com/617641/71924836-14120b80-3190-11ea-9730-70f3191f7ee6.png)

**Closed by zadam** 2020-01-07 19:56 UTC
