### ISSUE TITLE
Trilium becomes unresponsive after cut selection to sub-note

### ISSUE THREAD

**Issue by Raphapere** [zadam/trilium#1030] opened 2020-05-19 14:49 UTC
**Describe the bug**
Trilium becomes unresponsive after cut selection to sub-note

 **Steps to reproduce the behavior:**

1. Select text
2. Click on scissor icon (Cut & paste selection to a new note)
3. Trilium creates the new note but doesn't open this new note or any other note when clicked on it.
4. If I press CTRL + R It works again.

- OS: Linux Mint 19.3
- Trilium 0.42.2

[trilium-2020-05-19.log](https://github.com/zadam/trilium/files/4651202/trilium-2020-05-19.log)

**Comment by zadam** [comment] 2020-05-19 21:00
Hello, thank you reporting the issue. This was caused by deadlock in the code, this was fixed and will be released soon in a new patch version.

**Closed by zadam** 2020-05-19 21:00 UTC

**Comment by redyoshi49q** [comment] 2020-05-20 01:20
I've been experiencing this issue, too; thank you for the fix.

**Comment by Raphapere** [comment] 2020-05-22 14:14
I updated to 0.42.3 and now it's fine.

Thank you for the fix!
