### ISSUE TITLE
Not recognize existent db and not create new db.

### ISSUE THREAD

**Issue by maniasso** [zadam/trilium#539] opened 2019-05-27 11:33 UTC
I've built trilium using Docker file, however it was not able to recognize my previous DB. Docker logs show the following error:
Creating missing sync record for note_revisions yUZXybhMZY1W
Creating missing sync record for note_revisions zwNMAZO2wPEo
Trace: ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: no such column: noteIdError
    at wrap (/usr/src/app/src/services/sql.js:160:23)
    at Object.execute (/usr/src/app/src/services/sql.js:145:26)
    at cleanupSyncRowsForMissingEntities (/usr/src/app/src/services/sync_table.js:57:15)
    at fillSyncRows (/usr/src/app/src/services/sync_table.js:65:11)
    at Object.fillAllSyncRows (/usr/src/app/src/services/sync_table.js:94:11)
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at wrap (/usr/src/app/src/services/sql.js:166:13)
Trace: ERROR: Error executing transaction, executing rollback. Inner stack: Error
    at wrap (/usr/src/app/src/services/sql.js:160:23)
    at Object.execute (/usr/src/app/src/services/sql.js:145:26)
    at cleanupSyncRowsForMissingEntities (/usr/src/app/src/services/sync_table.js:57:15)
    at fillSyncRows (/usr/src/app/src/services/sync_table.js:65:11)
    at Object.fillAllSyncRows (/usr/src/app/src/services/sync_table.js:94:11)
Outside stack: Error
    at Object.transactional (/usr/src/app/src/services/sql.js:187:23)
    at Object.migrate (/usr/src/app/src/services/migration.js:49:23)
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at Promise (/usr/src/app/src/services/sql.js:205:21)
Trace: ERROR: error during migration to version 132: Error
    at wrap (/usr/src/app/src/services/sql.js:160:23)
    at Object.execute (/usr/src/app/src/services/sql.js:145:26)
    at cleanupSyncRowsForMissingEntities (/usr/src/app/src/services/sync_table.js:57:15)
    at fillSyncRows (/usr/src/app/src/services/sync_table.js:65:11)
    at Object.fillAllSyncRows (/usr/src/app/src/services/sync_table.js:94:11)
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at Object.migrate (/usr/src/app/src/services/migration.js:74:17)
Trace: ERROR: migration failed, crashing hard
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at Object.migrate (/usr/src/app/src/services/migration.js:75:17)

I also tried to create a new DB and the following erros happen when a new db is create

Creating missing sync record for branches zeC5hKvyH0me
Trace: ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: no such column: noteIdError
    at wrap (/usr/src/app/src/services/sql.js:160:23)
    at Object.execute (/usr/src/app/src/services/sql.js:145:26)
    at cleanupSyncRowsForMissingEntities (/usr/src/app/src/services/sync_table.js:57:15)
    at fillSyncRows (/usr/src/app/src/services/sync_table.js:65:11)
    at Object.fillAllSyncRows (/usr/src/app/src/services/sync_table.js:94:11)
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at wrap (/usr/src/app/src/services/sql.js:166:13)
Trace: ERROR: Error executing transaction, executing rollback. Inner stack: Error
    at wrap (/usr/src/app/src/services/sql.js:160:23)
    at Object.execute (/usr/src/app/src/services/sql.js:145:26)
    at cleanupSyncRowsForMissingEntities (/usr/src/app/src/services/sync_table.js:57:15)
    at fillSyncRows (/usr/src/app/src/services/sync_table.js:65:11)
    at Object.fillAllSyncRows (/usr/src/app/src/services/sync_table.js:94:11)
Outside stack: Error
    at Object.transactional (/usr/src/app/src/services/sql.js:187:23)
    at cls.init (/usr/src/app/src/routes/routes.js:80:38)
    at /usr/src/app/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/src/app/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/src/app/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/usr/src/app/src/services/cls.js:5:28)
    at router.(anonymous function) (/usr/src/app/src/routes/routes.js:75:38)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at checkAppNotInitialized (/usr/src/app/src/services/auth.js:55:9)
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at Promise (/usr/src/app/src/services/sql.js:205:21)
Trace: ERROR: post /api/setup/new-document threw exception: Error
    at wrap (/usr/src/app/src/services/sql.js:160:23)
    at Object.execute (/usr/src/app/src/services/sql.js:145:26)
    at cleanupSyncRowsForMissingEntities (/usr/src/app/src/services/sync_table.js:57:15)
    at fillSyncRows (/usr/src/app/src/services/sync_table.js:65:11)
    at Object.fillAllSyncRows (/usr/src/app/src/services/sync_table.js:94:11)
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at router.(anonymous function) (/usr/src/app/src/routes/routes.js:94:17)

Is there something I cando to overcome the error?

**Comment by zadam** [comment] 2019-05-27 19:53
Thank you for reporting this, it has been caused by bug in creating the initial database, fix is in 0.32.1-beta. But if you already have an existing database, then there might be some other problem - it should be recognized.

**Closed by zadam** 2019-05-27 19:53 UTC
