### ISSUE TITLE
v0.63.6 binaries release missing files

### ISSUE THREAD

**Issue by chrissy-hi** [zadam/trilium#4778] opened 2024-05-24 23:14 UTC
### Trilium Version

0.63.6

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows version 10

### Description

The v0.63.6 release for Windows and Mac are missing files including the executable file, so I am unable to install the application with the new updates.

**Comment by capi** [comment] 2024-05-26 09:41
(Almost) Duplicate of #4776, #4770.

For the Windows version:
> As a workaround, until zadam comes around fixing it: I've built the Windows version based on the release tag and attached it on a release in my fork. It's the first time I'm building a release myself, so please use at your own risk. It seems to run fine on my machine here.
https://github.com/capi/trilium/releases/tag/v0.63.6

**Closed** 2024-05-28 22:20 UTC
Labels: Type: Bug
