### ISSUE TITLE
Plaintext (and others) has a weak font on Windows

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#1493] opened 2020-12-18 03:37 UTC
Hi

Is there a way to change the font for these text file types on Windows?  The type has very weak contrast and bad aliasing. The same text  is totally different on Linux and more readable

See the image please

https://i.imgur.com/JH2nDmk.png

**Comment by lflare** [comment] 2020-12-18 06:38
Duplicate of #1489

**Closed** 2021-07-28 20:24 UTC
