### ISSUE TITLE
[UX] Increase 'note title' weight on `Jump to note` feature

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1640] opened 2021-02-15 09:05 UTC
## Issue
algolia based note searches (`Jump to note`, `Ctrl+L` in ckeditor, typing `@+word` in ckeditor) could have a better search algorithm.

For example, i have a note named `Promote cssClass`, and dozens note with `#cssClass` attribute set.
When i search for this note with the string `cssClass`, i would expect the following:
* note title: high priority
* note path: medium priority
* note attributes: low priority

Because for the moment this note apears at the very end of suggestions.

Thank you for hearing me !

**Comment by zadam** [comment] 2021-02-15 13:31
Hi, this should be fixed already in master/0.46. Coming (very) soon ...

**Comment by nil0x42** [comment] 2021-02-21 07:41
Hi ! I am currently using v0.46.1-beta, and `jump to note` search still has several issues.

# Issue
Here is an example of me trying to clone a note to `Tech knowledge / Hacking / Internal pentest` path:
![Screenshot_2021-02-21_07-17-49](https://user-images.githubusercontent.com/3504393/108618459-63f47600-7416-11eb-91d0-d917eb5bafc9.png)

Plenty of childs of `Interal pentest` appear as suggestion, but not the note itself, even if i scroll till the end.
It's very common that i want to jump to a note, and only grand-grand-grand childs of it are suggested, so  need to jump to them then go pack to the parent i'm interested in manually from the tree.

# Suggestions to fix
* In the example above, the wanted note didn't even appear, so in this case it might be a bug.
* For the most cases, a lot of childs of the note appear before the note we want, so showing shorter paths first should solve most issues (`ORDER BY path_depth ASC`, or maybe `OBRDER BY path_string_length ASC`)
* Another possibility would be to make each portion of the path clickable, but might look a little messy and prone to missclicks.

**Comment by zadam** [comment] 2021-02-21 21:20
Your suggested fix is exactly what was in place in 0.45 and older but the issue is that it did not take into account the quality of the matches. The first results in the search are there because it provides the most matches to the search token and thus are considered better than notes with shorter path but also fewer token hits ...

**Comment by nil0x42** [comment] 2021-02-22 06:57
Hum okay, it makes sense.
Maybe you could keep current algo & just ensure that shortest match appears at most at 10th position (or anywhere the user wouldn't need to scroll to seee it at first sight).

It would IMHO give the best of both worlds.

Indeed in my example, the match appeared at 8th position, so it's good like this. But in other cases i worry it could appear in a very more distant place.

**Closed** 2022-08-03 17:45 UTC
