### ISSUE TITLE
Some note content is off left margin?

### ISSUE THREAD

**Issue by LorenAmelang** [zadam/trilium#1238] opened 2020-09-15 00:18 UTC
0.43.3

Sometimes when I copy and paste content into a note, some lines shift past the left margin: 

![Trilium left margin](https://user-images.githubusercontent.com/1297090/93149400-1592bc80-f6ab-11ea-81af-e1b94037295a.JPG)

Nothing I've found in Trilium will change this, I can change all the formatting options and the left end is still hidden. 

I fixed one line by cutting it, using the program that strips formatting from things I paste to Excel, and re-inserting it. But that doesn't work on any of the other sections. 

Aha! When you paste the stripped plain text back to the note, it inherits the margin problem from the paragraph above, even if it is a blank line and you can't tell it has the problem. If you make sure to insert a fresh paragraph under a properly margined one, and then paste plain text, it works. 

Is this a bug, or am I missing something?

**Comment by zadam** [comment] 2020-09-16 08:17
Hi, does this happen with some particular content or randomly? If the former, could you link to text with which does this happen?

**Comment by LorenAmelang** [comment] 2020-09-16 19:52
Original is at:
https://www.sciencedaily.com/releases/2018/05/180524112351.htm

Tried to clip it again - actual content looks good:

![initial clip](https://user-images.githubusercontent.com/1297090/93382218-adf98000-f816-11ea-93fd-61ff890f96ae.JPG)

But I wanted the Date and Source, so I copied and Ctrl+V pasted. Today it got a big indent to the right, not the small one to the left:

![paste](https://user-images.githubusercontent.com/1297090/93382480-0761af00-f817-11ea-8bbb-293d06b67c69.JPG)

Tried to edit it, nothing I could find would remove the indent. The new content was top of the note content, anything I Ctrl+V pasted also got the indent. And the first paragraph of the previously good clipped content inherited it: 

![edit paste](https://user-images.githubusercontent.com/1297090/93382612-3710b700-f817-11ea-97d3-119ae054f277.JPG)

But I noticed the "Paste as Plain Text" menu option. Got a fresh copy and pasted it as plain text at the top of the note: 

![paste plain](https://user-images.githubusercontent.com/1297090/93382912-b69e8600-f817-11ea-9056-ae385050860b.JPG)

So I guess that's a solution...  But shouldn't there be a way to directly control the left margin? And maybe a way to show whatever invisible cues are causing it? 

`Aha! When you paste the stripped plain text back to the note, it inherits the margin problem from the paragraph above, even if it is a blank line and you can't tell it has the problem. If you make sure to insert a fresh paragraph under a properly margined one, and then paste plain text, it works.`

But it looks like you can't do that at the very top of the note...  There it inherits the existing indent from below, unless you use "paste as plain". Oh, and you can't just paste a few words, they will inherit the indent - even if pasted "plain". You have to paste multiple paragraphs as plain text to escape the margin!! 

Thanks for your support!

**Comment by zadam** [comment] 2020-09-16 20:28
Hi, thank you for the detailed analysis.

Unfortunately even with the link and described steps I can't get it to reproduce the issues.

> But shouldn't there be a way to directly control the left margin? And maybe a way to show whatever invisible cues are causing it?

Actually, there shouldn't be a way to control them - the actual issue is that there shouldn't be any margins at all. 

In general CKEditor (editing component) filters the HTML content and keeps only a known defined subset of elements (and CSS classes and so) which sort of simplifies pasted content but also keeps uniform look and removes these extra formatting. This normally works well but in your case it looks like something is failing there and pasted formatting is "leaking". So it seems to me like some CKEditor bug, but I can't really confirm that without being able to reproduce the issue myself.

In Trilium v0.44 there's a new content filtering for clipped content which should strip all these extra formatting and thus avoid this issue. For the just pasted content exhibiting this issue ... I recommend for now to work around this issue with "paste as plain text" and perhaps it will get fixed in CKEditor in the future ...

**Comment by LorenAmelang** [comment] 2020-09-17 03:44
I can't find an editor that will accept the copied text with the margins intact, but Excel will. Also accepts a text color so pale I couldn't read it, and a font size hopelessly tiny, so I set it to black, and huge.   

[Trilium Margin Trigger.xlsx](https://github.com/zadam/trilium/files/5236150/Trilium.Margin.Trigger.xlsx)

The Excel margins are hard to compare to Trilium because the label text is right justified. 

Here's what Vivaldi (Chromium) DevTools sees:

```
<dl class="dl-horizontal dl-custom">
<dt>Date:</dt>
				<dd id="date_posted">May 24, 2018</dd>
				<dt>Source:</dt>
				<dd id="source">European Society of Endocrinology</dd>
				<dt>Summary:</dt>
				<dd id="abstract">Brain activity and structure in transgender adolescents more closely resembles the typical activation patterns of their desired gender, according to new research. The findings suggest that differences in brain function may occur early in development and that brain imaging may be a useful tool for earlier identification of transgenderism in young people.
</dd>
				<dt class="no-print">Share:</dt>
				<dd class="no-print">
					<div id="share_top">
						<div data-url="https://www.sciencedaily.com/releases/2018/05/180524112351.htm" class="ssk-sm ssk-group">
						    <a class="ssk ssk-icon ssk-facebook" data-ssk-ready="true"></a>
						    <a class="ssk ssk-icon ssk-twitter" data-ssk-ready="true"></a>
						    <a class="ssk ssk-icon ssk-pinterest" data-ssk-ready="true"></a>
						    <a class="ssk ssk-icon ssk-linkedin" data-ssk-ready="true"></a>
						    <a class="ssk ssk-icon ssk-email" data-ssk-ready="true"></a>
						</div>
					</div>
				</dd>
			</dl>

CSS for <dd id="date_posted">:
dl.dl-custom dd {
    margin-left: 90px;  <-- the nasty margin...
    padding-bottom: 5px;

```

Probably not worth your time to struggle with, but I'm surprised you don't duplicate it. 

Oh - Firefox doesn't copy the formatting (except for the right justified "24-May-18" ???)

Both in the Excel file. 

Life has gotten complex beyond human abilities!

**Comment by zadam** [comment] 2020-09-17 06:39
> Probably not worth your time to struggle with, but I'm surprised you don't duplicate it.
> 
> Oh - Firefox doesn't copy the formatting (except for the right justified "24-May-18" ???)

I was also testing on FF and also observed that formatting is not copied.

Now I tested on Chrome and it looks different:

![](https://user-images.githubusercontent.com/617641/93429180-084f1b00-f8c1-11ea-9afb-54f67f3ba996.png)

And the structure:

![](https://user-images.githubusercontent.com/617641/93429208-13a24680-f8c1-11ea-8b33-1027d5424009.png)

So the issue here seems to be the inline styles. I thought CKEditor should filter them but for some reason doesn't.

**Comment by zadam** [comment] 2020-09-17 06:42
Perhaps I know why - margin-left is used by CKEditor for its own feature "indent block" and for that reason it is preserved.

You can play with indenting the block with TAB / SHIFT-TAB:

![](https://user-images.githubusercontent.com/617641/93429652-c8d4fe80-f8c1-11ea-9157-8aa0cc332950.png)

**Comment by LorenAmelang** [comment] 2020-09-17 19:19
Ah, thank you! I haven't really explored all those formatting options. 

Looks like 
https://ckeditor.com/docs/ckeditor5/latest/features/indent.html#snippet-indent
describes this. 

But maybe 
https://ckeditor.com/docs/ckeditor5/latest/features/remove-format.html
would be more powerful...  

Except which icon is the “Remove Format” button in the toolbar? I'm guessing "Tx" is the only one that doesn't have another meaning...???  But it isn't in my Trilium editor...  I just tried all the icons there, and they don't affect that formatting. Maybe you could include it - there are a lot of places I'd use it...  

The "M+down arrow" icon is strange - I guess it pastes whatever is on your clipboard to wherever you clicked in the paragraph to make the editor appear? While the editor has hidden the cursor? 

Is there a page somewhere that decodes all the icons in all those menus?

**Comment by zadam** [comment] 2020-09-17 19:31
Not all CKEditor features are included in Trilium. Although "Remove format" has been asked for recently in #1239 

> The "M+down arrow" icon is strange - I guess it pastes whatever is on your clipboard to wherever you clicked in the paragraph to make the editor appear? While the editor has hidden the cursor?

This is specifically for pasting Markdown content from the clipboard.

> Is there a page somewhere that decodes all the icons in all those menus?

No, there are just tooltips over the icons in the toolbar.

**Comment by LorenAmelang** [comment] 2020-09-17 20:10
`No, there are just tooltips over the icons in the toolbar.`

I expected so, but not in my system! Just tried all the themes - nothing. The individual background highlights, with mouse or pen over it, but no tooltip - not even in improper scaling locations. 

0.43.4
159
14
2020-08-27T23:58:58+02:00
dc288fb18c7622f6e08c574888dc0e8c90e544c2

Interesting...  I copied your labels, something stripped them. They show in my local text editor...  Not here. 

`
Homepage: | https://github.com/zadam/trilium
-- | --
0.43.4
159
14
2020-08-27T23:58:58+02:00
dc288fb18c7622f6e08c574888dc0e8c90e544c2
`

Win 10 1909
18363.1082

**Closed** 2022-08-03 17:30 UTC
