### ISSUE TITLE
FR: Drag and drop documents from file managers

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#414] opened 2019-02-18 18:42 UTC
Hi

It would be very helpful if one can drag documents and drop into Trilium, both as an attachment and as a new document. If it is a recognized attachment and it is text based it would insert is the content.

At the moment when I try such action, it pretends that it will do it but I get a pop up that says "moving cloning here would create cycle"

I am using the Linux version.

**Comment by zadam** [comment] 2019-02-18 19:22
This is planned, I created an issue for this a week ago in #406

**Comment by gerroon** [comment] 2019-02-18 19:38
Thanks I appreciate it, this would make it great for documentation

**Comment by gerroon** [comment] 2019-02-18 19:40
Also my request is abit more extended than the one you opened. I personoanlly would like to be able to drop documents as content of a note.

thanks

**Comment by zadam** [comment] 2019-02-26 22:02
Import support is now more extended - drag & drop on tree (or note detail) works and HTML & MD files are by default imported as new text notes (not attachments). Will be released soon.

**Closed by zadam** 2019-02-26 22:02 UTC

**Comment by gerroon** [comment] 2019-02-26 22:29
Thanks for the additions

**Comment by gerroon** [comment] 2019-03-01 19:34
> MD files are by default imported as new text notes (not attachments

Ok I just tested the latest release and I am not getting that work properly. It still adds it as an attachment. I just dragged and dropped an README.md

I am on Win 10 0.30.2-beta

**Comment by gerroon** [comment] 2019-03-01 19:36
Ok I did  a bit more testing, it is a bit confusing

D&D of an .md onto the tree creates an attachment file

D&D of an .md into an empty document area imports the content but it still creates  an attachment file in the tree

**Comment by zadam** [comment] 2019-03-03 21:09
Thanks for report, looks like your issues were caused by the windows not giving correct MIME types (I was developing on linux which worked fine). I fixed that by detecting from the file extensions instead which works on windows as well. Fix is in 0.30.3-beta.

**Comment by gerroon** [comment] 2019-03-03 23:37
@zadam

Thanks for the new fix. It works, almost. I can import an .md as a regular not but it imports as text file. And the issue with that is this, then I need to convert it to .md from regular text, and that totally messes up the note and converts to that html thing.

thanks for the new fixes and additions again.

**Comment by zadam** [comment] 2019-03-04 09:48
If you right-click on the tree and then Import, you can configure the import - specifically if you uncheck "Import HTML, Markdown and TXT as text notes if it's unclear from metadata" then .md file will be imported as a code note.

Drag & drop uses default settings which imports markdown as text file.

**Comment by gerroon** [comment] 2019-03-04 17:09
Thanks I will take a look at it.

**Comment by gerroon** [comment] 2019-03-07 05:25
@zadam 

Ok I tried your recommendation. It works only if I go through that right click import, otherwise those settings are not remembered for drag and drops on Windows as far as I can tell.


thanks

**Comment by zadam** [comment] 2019-03-07 08:23
Yes, drag & drop always uses default settings.

**Comment by gerroon** [comment] 2019-03-07 15:56
Sure but that does not make things easy, One always end up needing to use the import menu to get the right format. 

Will it be possible to change those defaults so the user can actually utilize the drag and drop approach?

thanks
