### ISSUE TITLE
Inheritable Attributes doesnt work for SAVED SEARCH

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1260] opened 2020-09-22 20:24 UTC
Search results can't be inheriteble from SAVED SEARCH's Attribute
E.g I want all reasults to be **inheritable**(**@autoReadOnlyDisabled**)from PARENT SAVED SEARCH.But it seems to be not working as well
I tried normal note's attribute then works perfectly (All child notes are autoReadOnlyDisabled)

Another Question is about Seach syntax:
Can we add a new syntax way to avoid to search "SAVED SEARCH"as result?
My current solution is using @in!=(**Saved Search's ID**) to avoid them from appearing in my Search.
Cos，Sometimes I just wanna find search results for notes(NOT SAVED SEARCH)
Thanks

**Comment by zadam** [comment] 2020-09-23 21:14
Attributes defined on search note are not inherited to the found results even if marked as inheritable. That is by design. Search notes are just special. (not sure if this is what you're asking about)

**Comment by Rsose** [comment] 2020-09-24 12:20
> Attributes defined on search note are not inherited to the found results even if marked as inheritable. That is by design. Search notes are just special. (not sure if this is what you're asking about)

Yes thats I mean,this is not big problem at moment.
Thanks for anwsering **any** question

**Closed** 2020-09-24 12:20 UTC
