### ISSUE TITLE
(Feature request) Internal Link to headers

### ISSUE THREAD

**Issue by casudo** [zadam/trilium#4087] opened 2023-07-09 11:06 UTC
### Describe feature

Currently, it only seems to be possible to link to notes directly, but not to headers inside the note.
![image](https://github.com/zadam/trilium/assets/55252063/665a2adb-62c0-4082-84e9-be24265f94a8)

As you can see, I can link to the subnote "Testsubnote". However, I would like to link to a specific header inside the "Testsubnote" file.

This could ideally look like this:
![image](https://github.com/zadam/trilium/assets/55252063/2510a5bc-4579-415f-ae4e-0f3d93375463)

**Comment by zadam** [comment] 2023-07-09 21:54
Closing as duplicate of #1021

**Closed by zadam** 2023-07-09 21:54 UTC
Labels: Type: Enhancement
