### ISSUE TITLE
Editable attributes in sidebar

### ISSUE THREAD

**Issue by sharifkhalladi** [zadam/trilium#884] opened 2020-02-27 21:29 UTC
It would be useful to be able to edit attributes directly in the sidebar, without having to show the dialog. This would allow for much quicker application of labels etc.

**Comment by zadam** [comment] 2020-02-28 14:25
Yes, editing attributes is currently cumbersome and I have been thinking about in-place editing for a long time. It is one of the highest priority items on my backlog, unfortunately it is also a bit difficult to get it right.

**Comment by fivestones** [comment] 2020-04-23 18:50
I'd love to be able to just type in the text of a note `@attribute=value` and have it automatically become an attribute.

Also what would be great would be the ability to set a shortcut key for specific attribute=value attributes. E.g., I want to be able to add @anAttribute=itsValue and I can set a shortcut like ctrl-shift-a and when I type this shortcut that specific attribute and its value are applied to the current note.

**Comment by zadam** [comment] 2020-04-23 20:07
> I'd love to be able to just type in the text of a note @attribute=value and have it automatically become an attribute.

I agree this would be ideal and I've thought about this a lot. Technically it is possible, but ...

The problem is that attributes are really its own entity. So we allow them to be defined inline in the text and on save we parse them into Attribute entities. But then there are questions like - what if we remove the Attribute entity from e.g. script or whatever, do we also remove it from the text? What if the script then adds the Attribute back, should we again put it into the text? But where?

I could never come up with satisfactory answers to these questions and it always seemed kind of confusing in those situations.

**Comment by leips** [comment] 2020-05-24 17:45
> I'd love to be able to just type in the text of a note `@attribute=value` and have it automatically become an attribute.
> 
> Also what would be great would be the ability to set a shortcut key for specific attribute=value attributes. E.g., I want to be able to add @anAttribute=itsValue and I can set a shortcut like ctrl-shift-a and when I type this shortcut that specific attribute and its value are applied to the current note.

I just discovered Trilium and finally I found something that fit in my workflow.

The only thing that I miss A LOT is the tag/attribute creation inside the note. 

It's possible to do with a script? For example, select a word or a phrase and click to execute the script and convert to attribute?

**Comment by zadam** [comment] 2020-09-21 11:30
The original issue - editing attributes without opening a dialog, has been implemented in 0.44 and thus closing ...

**Closed by zadam** 2020-09-21 11:30 UTC
Labels: Difficulty: Hard, State: Under Debate, Type: Enhancement
