### ISSUE TITLE
PDF box is blank

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#1976] opened 2021-05-24 16:47 UTC
0.47.3 (desktop .deb, KDE neon, ubuntu based)
![image](https://user-images.githubusercontent.com/69441971/119379778-6a151f80-bcaf-11eb-8aa5-094dd86ed386.png)

It works in browser (firefox latest)
![image](https://user-images.githubusercontent.com/69441971/119379902-8e70fc00-bcaf-11eb-8a95-c527957c0d15.png)

When I click open the file opens just fine in my PDF editor, so file seems to be fine.

**Comment by zadam** [comment] 2021-05-25 18:11
Hi, this is a known issue which appeared after upgrade to electron 13. There has been some PDF related fixes in the last electron beta releases so I will need to check it again ...

**Comment by ehamminga** [comment] 2021-06-07 03:40
If you're talking about the permission issue [#29252](https://github.com/electron/electron/pull/29252) for the PDF viewer in Electron, that seems to be fixed in version 13.1.0

**Comment by zadam** [comment] 2021-06-11 18:34
@ehamminga tested this with electron 13.1.2 and the issue persists :-(

**Comment by ehamminga** [comment] 2021-06-14 22:34
bummer

**Comment by zadam** [comment] 2021-06-15 19:19
bug report is here: https://github.com/electron/electron/issues/29326

Looks like electron devs can reproduce it and assigned it a high priority.

**Comment by zadam** [comment] 2021-06-25 19:27
PDF is again working with electron 13.1.4, I'm just releasing 0.47.5.

**Closed by zadam** 2021-06-25 19:27 UTC

**Comment by sigaloid** [comment] 2021-06-25 19:36
Strangely I was getting this issue on KDE Neon, not windows as mentioned in that other issue and in the electron issue. But thanks for the fix, awaiting update

**Comment by zadam** [comment] 2021-06-25 22:09
Interesting. I'm not sure if it's windows specific, it's just that in my case on Ubuntu it always worked and it was broken in Windows only. Anyway I hope it's going to work now everywhere :)

**Comment by ehamminga** [comment] 2021-06-25 22:56
Can confirm. PDF works again on Windows
