### ISSUE TITLE
(Bug report) Table of Contents (ToC) is uncloseable in split note view

### ISSUE THREAD

**Issue by perfectra1n** [zadam/trilium#4093] opened 2023-07-13 18:10 UTC
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10

### Description

The Table of Contents becomes uncloseable when using the split pane functionality:
![trilium_ePhqQMhKg9](https://github.com/zadam/trilium/assets/2390633/079605a6-3c9c-404e-b601-4572550114e8)

The highlighting and unhighlighting of the `x` isn't me clicking, that's the frontend constantly stuck in some weird case 👀 

No matter how fiendishly I click, I can't close the ToC lol. If there's anything more I can help with, please let me know. Obviously something weird is going on in `toc-widget`...

The `aria-describedby` value is changing over and over again when it's highlighted...
![image](https://github.com/zadam/trilium/assets/2390633/8151e949-dbf2-4c7d-99fd-d1dab53717f6)

**Comment by XXXJetfireXXX** [comment] 2023-07-14 00:27
Hmm, I wasn't able to reproduce the bug, it works fine with splits on my side: when I open two notes in split mode, both have TOC; then, I can close it for each split individually. Do you have `#toc` label in the second note or did you change this setting?
![image](https://github.com/zadam/trilium/assets/43646178/000ccf99-e436-4215-846a-115317ee7b41)

**Comment by perfectra1n** [comment] 2023-07-14 04:25
Hmmm, that's interesting, I have it set to `-1` so that it always shows...could be part of the issue lol
<img width="1101" alt="image" src="https://github.com/zadam/trilium/assets/2390633/78b7830d-c7af-4b2c-96cd-7d627384e79b">

**Comment by XXXJetfireXXX** [comment] 2023-07-14 06:07
MacOS? I thought you were using the version for Windows, as it is defined in the issue.

**Comment by perfectra1n** [comment] 2023-07-14 15:34
Yes I was just mentioning that the issue is happening on my MacOS as well :)

**Comment by zadam** [comment] 2023-07-15 09:19
Hi, I managed to reproduce it and fix it in 0.61 branch. It seems to be some visual/placement glitch.

Thanks for reporting.

**Closed by zadam** 2023-07-15 09:19 UTC
Labels: Type: Bug
