### ISSUE TITLE
(Bug report) Recursion? {"message":"Maximum call stack size exceeded"}

### ISSUE THREAD

**Issue by yelvington** [zadam/trilium#4442] opened 2023-11-15 23:26 UTC
### Trilium Version

0.61.11

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

### Description

My Trilium now won't do anything other than print {"message":"Maximum call stack size exceeded"} and the web UI is no longer accessible. Same thing happens when I use the Android app.

How I got here: I created a note, intending to use it as a folder to organize a collection of unorganized documents.

I believe that I accidentally "moved" that note into itself, rather than moving one of the unorganized notes. It looks like I created a recursion.

This shouldn't be possible, or at least not so easy. :-)

Now I can't get into the UI to clean things up / delete the offending note/ use Trilium in any way. 

Is there a way to delete without going into the UI? 

I don't want to nuke everything and recover from a pre-upgrade export zipfile, as I would lose a bunch of work. 

### Error logs

17:46:58.920 304 GET /api/note-map/iAIsjX3zsAAj/backlink-count with 11 bytes took 2ms
17:47:22.274 JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (https://.com/trilium/assets/v0.61.11/app/services/utils.js:305:19)
    at consumeFrontendUpdateData (https://.com/trilium/assets/v0.61.11/app/services/ws.js:179:25)
    at executeFrontendUpdate (https://.com/trilium/assets/v0.61.11/app/services/ws.js:90:35)
    at WebSocket.handleMessage (https://.com/trilium/assets/v0.61.11/app/services/ws.js:114:15), reloading frontend.
Stack: Error
    at logError (https://xxx.com/trilium/assets/v0.61.11/app/services/ws.js:24:20)
    at consumeFrontendUpdateData (https://xxx.com/trilium/assets/v0.61.11/app/services/ws.js:182:13)
17:48:41.076 304 GET /api/notes/6oxP7QWvzEyB/blob with 968 bytes took 3ms
17:48:41.087 304 GET /api/note-map/6oxP7QWvzEyB/backlink-count with 11 bytes took 2ms
17:48:41.097 204 PUT /api/options with 0 bytes took 7ms
17:48:42.741 ERROR: get /api/search-templates threw exception: 'Maximum call stack size exceeded', stack: RangeError: Maximum call stack size exceeded
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1246:23)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
17:48:42.798 JS Error: 500 GET search-templates - Maximum call stack size exceeded
Stack: Error
    at Object.logError (https://xxx.com/trilium/assets/v0.61.11/app/services/ws.js:24:20)
    at Object.throwError (https://xxx.com/trilium/assets/v0.61.11/app/services/toast.js:100:8)
    at reportError (https://txxx.com/trilium/assets/v0.61.11/app/services/server.js:222:22)
    at async Object.error (https://tx.com/trilium/assets/v0.61.11/app/services/server.js:141:21)
17:48:44.055 ERROR: get /api/search-templates threw exception: 'Maximum call stack size exceeded', stack: RangeError: Maximum call stack size exceeded
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1246:23)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
    at BNote.isHiddenCompletely (/var/www/trilium/src/becca/entities/bnote.js:1256:36)
17:48:44.201 JS Error: 500 GET search-templates - Maximum call stack size exceeded
Stack: Error
    at Object.logError (https://tx.com/trilium/assets/v0.61.11/app/services/ws.js:24:20)
    at Object.throwError (https://t.x.com/trilium/assets/v0.61.11/app/services/toast.js:100:8)
    at reportError (https://tx.com/trilium/assets/v0.61.11/app/services/server.js:222:22)
    at async Object.error (https://x.com/trilium/assets/v0.61.11/app/services/server.js:141:21)
17:48:45.511 204 PUT /api/options with 0 bytes took 8ms

**Comment by zadam** [comment] 2023-11-15 23:42
Hello, sorry for the trouble. It indeed seems like there's some recursion - there is a protection against forming a graph cycle, but looks like you manage to "hack" it somehow. 

Have you tried restarting the whole app? There's a consistency check which also looks for these recursion in the database and tries to fix them.

I will look into this in more detail tomorrow.

**Comment by yelvington** [comment] 2023-11-15 23:52
Thanks, I found https://github.com/zadam/trilium/wiki/Troubleshooting#broken-note-crashes-trilium and was able to delete the offending note, so my immediate problem is resolved, but the question remains as to how I fatfingered this.

**Comment by zadam** [comment] 2023-11-16 22:32
Hello, I managed to reproduce and fix the issue, it will be released in the next patch release.

The workaround is to restart the app - consistency checks catch the problem and untie the cycle.

**Closed by zadam** 2023-11-16 22:32 UTC
Labels: Type: Bug
