### ISSUE TITLE
28.0-beta - render issue in WYSIWYG notes

### ISSUE THREAD

**Issue by octoshrimpy** [zadam/trilium#358] opened 2019-01-18 22:17 UTC
Not even sure how to explain it.

editor seems to think it's empty after typing something into it

you can view it [here](https://i.imgur.com/XmAKf3I.gifv)

**Comment by zadam** [comment] 2019-01-18 23:17
Interesting ... I can reproduce it, but only with this empty list. I think it's because the editor is still technically empty "textwise" - it has only (list) formatting.

**Comment by xingped** [comment] 2019-01-19 07:43
I'm seeing the same issue on the Windows 0.28.1-beta build. I created a new note and it was populated with quote boxes, but I couldn't delete anything and backspace would never work and enter started failing shortly thereafter too.

**Comment by xingped** [comment] 2019-01-22 20:59
@zadam It might be, but in my head I was thinking "maybe the reason backspace won't work is because it already thinks the note is empty" similar to how the placeholder text was showing as if it were it empty. I'll see if I can try to reproduce the issue and try to record it or something for you.

**Comment by zadam** [comment] 2019-12-21 13:21
Closing as this was an issue with older versions of CKEditor but not anymore ...

**Closed by zadam** 2019-12-21 13:21 UTC
