### ISSUE TITLE
[bug report] Duplicate Display of Child Notes

### ISSUE THREAD

**Issue by hjianyi** [zadam/trilium#1191] opened 2020-08-15 16:31 UTC
Trilium Version: 0.43.3
OS: macOS Catalina (Version 10.15.6)

[screenshots](https://www.dropbox.com/sh/6mlxfztjcsf5pkj/AAAEDeBtgA41n6EbfZMF7hqca?dl=0)

### Step 1: 
Select a `container note` that 
1. has no content so that it displays its child notes. (can be root) 
2. has a `child note` that has no content and with 1 or more child notes

### Step 2:
Select the `child note` in `container note`'s  `note-detail-book-content` view.

### Step 3:
There's no step 3.

Reload will make duplicated notes disappear.

**Comment by zadam** [comment] 2020-08-15 20:31
Hello, thank you for reporting this issue.

This was caused by multiple activation of the note upon the click event. This was now fixed.

**Closed** 2020-08-15 20:30 UTC
