### ISSUE TITLE
(Bug report) Hitting Ctrl-F multiple times opens multiple 'Find' search bars

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#2615] opened 2022-02-07 04:39 UTC
### Trilium Version

0.50.1

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

MacOS

### Description

![Screen-Recording-2022-02-06-at-1](https://user-images.githubusercontent.com/10717998/152725404-fa7ec103-e35d-41a0-9f88-f5b2dd4ecf81.gif)
This may be fixed when the [CKEeditor search is implemented(?)](https://github.com/zadam/trilium/issues/2254#issuecomment-948911953)

**Comment by meichthys** [comment] 2022-02-07 19:01
Also not relevant for web versions since `ctrl-f` uses the built-in browser search.

**Comment by wunter8** [comment] 2022-02-07 20:01
Confirmed on Ubuntu in latest Trilium

**Comment by zadam** [comment] 2022-02-07 21:56
Yes, the search sucks. There is actually already CKEditor search, but it doesn't work with the shortcut and needs to be clicked on the toolbar:

![image](https://user-images.githubusercontent.com/617641/152878795-3606b3f2-43b4-4036-bb4e-232993a866e4.png)

**Comment by antoniotejada** [comment] 2022-04-22 20:24
Give this widget a try #2806

**Comment by meichthys** [comment] 2022-04-22 20:41
> Give this widget a try #2806

@antoniotejada  Nice work 👍
Could you follow up here if you find a way for it to work without having to tag each note?

**Comment by sigaloid** [comment] 2022-04-22 20:43
You can go to the root note, add the `#findWidget` attribute, and mark it as inheritable. Then every note will have that tag :smile:

**Comment by meichthys** [comment] 2022-04-22 20:43
Also, in case anyone else is looking for an alternative search, the `Ctrl - J` then `Ctrl - Enter` search is quite useful for searching all/multiple notes.

**Comment by antoniotejada** [comment] 2022-04-22 20:49
> > Give this widget a try #2806
> 
> @antoniotejada Nice work 👍 Could you follow up here if you find a way for it to work without having to tag each note?

Haha thanks, the tag is just a safety measure while I'm developing it, if you are so confident in the widget :-)) @sigaloid's trick is a good option. Another option is to remove that condition from the code (ctrl+f ;-) in the widget code for "hasLabel" and remove it ).

```javascript
isEnabled() {
        return super.isEnabled()
            && ((this.note.type === 'text') || (this.note.type === 'code'))
            && this.note.hasLabel('findWidget');
}
```

**Comment by zadam** [comment] 2022-08-03 18:19
Closing since there's a new find dialog now.

**Closed by zadam** 2022-08-03 18:19 UTC
Labels: Type: Bug
