### ISSUE TITLE
Locked up after cancelled Print command

### ISSUE THREAD

**Issue by bkidwell** [zadam/trilium#650] opened 2019-10-03 00:02 UTC
**Summary:** Print Note; cancel print; UI is locked up now
**Expected result:** If you cancel the desktop Print dialog box, Trilium should resume operation normally.

I activated Note Actions → Print Note, then I decided to cancel the Print action. Most of the UI is locked up now. The following things are **not responding** to input events:

* navigation tree
* Note Actions button
* shortcuts toolbar at top
* everything else I try that isn't the CKEditor frame

I shut down Trilium and restarted it and I was able to immediately experience the same failure in the same way again. Log entries from the last attempt are attached.

"appVersion": "0.34.3" -- Windows desktop build (also 0.35.1; see below comment from bkidwell)
[trilium.log](https://github.com/zadam/trilium/files/3683887/trilium.log)

**Comment by zadam** [comment] 2019-10-03 08:33
Hello, thanks for the report.

I can't reproduce it (testing on 0.35.1). Did you try perhaps on a different note in case it was perhaps something note content specific?

**Comment by bkidwell** [comment] 2019-10-04 01:53
I'll try it with 0.35.1 in a few days, and do my best to find any example test cases that change my result, or any other evidence I can gather. Feel free to reply and ask where I went if it's been a week. :^)

**Comment by bkidwell** [comment] 2019-10-08 17:12
I upgraded to the latest release "trilium-windows-x64-0.35.1.zip" and tried it again, and I got the same result.

The page has only a title and one paragraph on it. The selected printer when I CANCELLED the print request was "Microsoft Print to PDF".

I'm running Windows 10 Enterprise 64-bit build 17134.

I didn't try this on another OS platform; I assume if it's a cross-platform issue someone else would have noticed already.

Is there anything else I can say that will help diagnose or make the problem reproducible?

Log file: [trilium-2019-10-08.log](https://github.com/zadam/trilium/files/3703679/trilium-2019-10-08.log)
Screenshot of the page I tried to print: [sandbox-page](https://user-images.githubusercontent.com/723919/66416747-90982100-e9cc-11e9-8110-f7105808c4c8.png)
Notebook subtree containing the page I tried to print: [notebook.tar.zip](https://github.com/zadam/trilium/files/3703683/notebook.tar.zip)

**Comment by zadam** [comment] 2019-10-08 17:15
Hmm, I see. For me print works fine in windows 10 64 bit as well, also tested with Microsoft Print to PDF.

Not sure what this could be, but I'll try to experiment a bit.

**Comment by bkidwell** [comment] 2019-10-08 17:17
This problem is about choosing the Print command and then CANCELING the request -- Doing so causes everything but the CKEditor widget in Trilium to lock up and stop responding. Did you cancel a print command?

**Comment by zadam** [comment] 2019-10-08 19:14
Oh, I see, I have overlooked that "cancel" ... so yeah, I can reproduce this problem. Happens only in the desktop version and it turns out it's a bug in electron - https://github.com/electron/electron/issues/20426

**Comment by TerrapinSoftware** [comment] 2019-10-11 11:07
Easy to reproduce with the electron-quick-start repo. Just add this line to index.html:

``<button onclick="window.print()">Click me</button>``

Then click the button and choose Cancel. Try to click that button again. No reaction. Also, the devtools breakpoints do not work anymore. Try to set an event listener breakpoint on the click event...

**Please increase the priority of this bug. Every electron app that supports printing cal fall victim to complete data loss!**

**Comment by zadam** [comment] 2019-10-11 11:13
@TerrapinSoftware this should be probably send to the bug in the electron repo, not here ...

**Comment by TerrapinSoftware** [comment] 2019-10-11 11:15
Ah yes. Sorry. Done. Added comment to electron bug #20426.

**Comment by zadam** [comment] 2020-03-08 17:05
This is now fixed in master with new electron.

**Closed by zadam** 2020-03-08 17:05 UTC
